### ISSUE TITLE
Data Analytics for "has a ransomware detonated"

### ISSUE THREAD

**Issue by runt1me** [runt1me/stormcloud#11]
I will start out by saying that this might be a completely dumb idea because it may be incredibly obvious when a ransomware has executed on a device. Frankly I need to put some more time into researching how different RW variants work to see if they try to be sneaky or if detection is always easy.

Nonetheless, we could perhaps look at holistic analytics across a device (or network for that matter):
-files that don't normally update are updating
-lots of files changing in a very short period of time
-file sizes or extensions changing in a predictable manner

Estimated story points: ??

**Comment by runt1me** [comment]
Recently learned that malware samples can be found at vx-underground (https://www.vx-underground.org/malware.html). This could be a good place to find Ransomware samples for our testing. Obviously do not touch anything if you do not know what you are doing so that you don't accidentally RW yourself.

@EccentricKnight thoughts on this?

**Comment by EccentricKnight** [comment]
@runt1me Based on where the business has been going I think this is a nice feature to consider in future-state but don't think we'll get there soon.

Seems like it could be an entire product/company in itself, don't want to waste cycles right now.

**Comment by runt1me** [comment]
@EccentricKnight Agreed, I'll close as wontfix.
