### ISSUE TITLE
Better Installer UI

### ISSUE THREAD

**Issue by runt1me** [runt1me/stormcloud#33]
The installer now contains more or less baseline functionality (at least for Windows); but the UI leaves something to be desired. [This medium article](https://medium.com/@fareedkhandev/modern-gui-using-tkinter-12da0b983e22) refers to a CustomTkinter library which may be an option for improving the GUI's design. 

I'd like to solicit input from the team on exactly what level of effort should go into this prior to the MVP release.

Estimated story points: 8

**Comment by runt1me** [comment]
One particular improvement that would be nice: adding a textbox field for the API key with "live validation" of the key.

**Comment by EccentricKnight** [comment]
@runt1me Would you consider this resolved?
