### ISSUE TITLE
Client should run in background

### ISSUE THREAD

**Issue by runt1me** [runt1me/stormcloud#34]
Currently the client pops up a command window when it executes. It should run somehow in the background, maybe in the System Tray for Windows, or otherwise invisible to the user.

Estimated story points: 5

**Comment by runt1me** [comment]
https://stackoverflow.com/questions/9494739/how-to-build-a-systemtray-app-for-windows

**Comment by runt1me** [comment]
Use this for building: pyinstaller --noconsole --onefile --hidden-import pkg_resources --hidden-import infi.systray stormcloud.py

**Comment by EccentricKnight** [comment]
@runt1me Would you consider this resolved?

**Comment by runt1me** [comment]
Client now runs in background, but system tray app doesn't have any options. Need to figure out which options to provide and add associated functionality.

**Comment by EccentricKnight** [comment]
Should this be a separate issue?

**Comment by runt1me** [comment]
Ideas for options to include in the system tray menu:
1. **A "restore" option** which brings up some type of dialog, maybe communicates with the server to fetch available files/versions to restore. Or maybe just redirects to the SCC.
2. **A "reconfigure" option** which brings up the settings and allows them to make changes
3. **A stop option** which turns off Stormcloud

We should also change the text to display "Stormcloud - Backup in Progress" when files are being backed up. Or something similar. This will make it look more similar to other apps that run in the system tray.

I don't think items 1/2 should be required for the MVP but should be completed down the road.

**Comment by runt1me** [comment]
Finished testing on option 3 and changed the "backup now" button to log that the user clicked the button, since the backup is always running. We can eventually change this behavior if we find a better way to asynchronously kick off a backup (maybe interrupting the sleep timer). For now it doesn't seem important enough to me, especially since the sleep timer is 90 seconds by default.

Cleanup is complete as of 4b7de87. Closing this issue.
