### ISSUE TITLE
Better way for client to change settings after install

### ISSUE THREAD

**Issue by runt1me** [runt1me/stormcloud#44]
Currently, if a client wanted to make changes to the directories that they have backed up after the install has completed, they would need to modify the settings file by hand. This could be difficult for a non-technical user; we should provide an interface to do it.

Possible ways to get this done:

- The Stormcloud client, when running, could have a GUI that displays the status of the backup, etc. as it is happening. We could render and display the settings to them and provide a way for them to add/change paths there.
- We could provide an interface in Stormcloud Web for them to add/change a path. Then, the server could send that info to the client as a new "tasking" that the client receives and executes upon its next check-in with the server.

The latter approach does institute a new kind of paradigm where the server is telling the client what to do, so we would need to carefully consider the consequences of doing that and make sure we are doing it correctly.

Either approach requires a significant amount of re-architecting (first approach would require us to create a GUI for the client, currently there is none) so I don't think this is feasible for the MVP, but down the road it feels necessary.

Estimated story points: 10

**Comment by EccentricKnight** [comment]
@runt1me The command center seems like a natural place to incorporate this. We could probably build a file-explorer style interface that allows users to check/uncheck files and folders to be backed up. Unless you want to build a client-side application but that feels like a lot more work.

**Comment by runt1me** [comment]
Closing as complete, user now has the ability to change backup folder settings via SCC.
