### ISSUE TITLE
Stormcloud Icon for Client / Installer

### ISSUE THREAD

**Issue by runt1me** [runt1me/stormcloud#45]
We need an icon for the executable. I think they can be the same for the client and the installer. Or maybe we can just use the standard MSI icon for the installer? 

Internet research suggests that we may be able to include this with pyinstaller:
`pyinstaller.exe --onefile --icon="test.ico" stormcloud.py`

More links for pyinstaller settings: [one](https://stackoverflow.com/questions/9960583/how-do-you-make-an-installer-for-your-python-program) [two](https://stackoverflow.com/questions/29291113/pyinstaller-setting-icons-dont-change)

Estimated story points: 2

**Comment by EccentricKnight** [comment]
@runt1me The current version of the stormcloud icon looks good. Closing this for now.

![image](https://github.com/runt1me/stormcloud/assets/115486397/978b1ffa-1a39-43c3-840c-02e21c7d122a)
