### ISSUE TITLE
PyInstaller switches

### ISSUE THREAD

**Issue by runt1me** [runt1me/stormcloud#50]
Opening this issue to document possible options to use with pyinstaller until we get this nailed down.

### Standard pyinstaller arguments for GUI application
`--onefile --noconsole --icon=stormcloud.ico`

### Change name as it appears in task manager? (Untested)
`--win-private-assemblies --name "Stormcloud Backup Engine"`

### Hidden imports from infi.systray library
`--hidden-import pkg_resources --hidden-import infi.systray`

### Manifest file to require administrative permissions
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity version="1.0.0.0" name="Stormcloud.app"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>
</assembly>
```

Save as `app.manifest` and include the switch: `--manifest app.manifest`

### All together
`pyinstaller --onefile --noconsole --icon=stormcloud.ico --win-private-assemblies --name "Stormcloud Backup Engine" --hidden-import pkg_resources --hidden-import infi.systray --manifest app.manifest stormcloud.py`

### Signing code after it is built
https://express.esigner.com/

**Comment by runt1me** [comment]
Tagging @EccentricKnight for awareness

**Comment by runt1me** [comment]
Icon doesn't appear to be properly passed to the .exe that ends up in the system tray. Maybe a pyinstaller problem since apparently it runs 2 processes?

**Comment by EccentricKnight** [comment]
Is this resolved with the pyinstaller recompile?

**Comment by runt1me** [comment]
Closing as documentation has been moved to the Wiki.
