### ISSUE TITLE
Update non-dynamic web content

### ISSUE THREAD

**Issue by EccentricKnight** [runt1me/stormcloud#68]
Currently have placeholders in place, need to update web pages with real content for the following pages:

1. https://apps.darkage.io/home.html
2. https://apps.darkage.io/about_us.html
3. https://apps.darkage.io/dark_age_faq.html
4. https://apps.darkage.io/pricing.html
5. https://apps.darkage.io/stormfront_blog.html
6. https://apps.darkage.io/privacy_policy.html
7. https://apps.darkage.io/terms_and_conditions.html
8. https://apps.darkage.io/contact_us.html

Need to make sure all buttons work properly. Pages with buttons include:

https://apps.darkage.io/pricing.html
https://apps.darkage.io/stormfront_blog.html
https://apps.darkage.io/contact_us.html
https://apps.darkage.io/create_account.html
https://apps.darkage.io/login.html
https://apps.darkage.io/password_reset.html

Also need to update the following on the create account and login pages:

1. Social button formatting (should be circular)
2. Social button links

**Comment by EccentricKnight** [comment]
Updated content on home/about_us/pricing pages

**Comment by runt1me** [comment]
Closing as complete, as most of the static content has been moved to Squarespace, and SCC is pretty-well tested at this point.
