### ISSUE TITLE
Marketing Stuff

### ISSUE THREAD

**Issue by EccentricKnight** [runt1me/stormcloud#71]
1. Come up with list of businesses for Ryan and potential clients
2. Find good demo video from other businesses that Ryan can do for DATG
3. Emphasize to potential clients that's we'll very if they're a good fit
4. Facebook page, beef up LinkedIn page, IG page have it all linked to website and Twitter page
5. Use AI pictures and GPT to post blogs and pictures
6. Use mechanism to post across socials

**Comment by EccentricKnight** [comment]
@runt1me @datdb97 Is sales team happy with/working on this?

**Comment by runt1me** [comment]
Sales has a marketing plan in place. Closing this issue as complete.
