### ISSUE TITLE
Cleanup install logic

### ISSUE THREAD

**Issue by runt1me** [runt1me/stormcloud#79]
When performing an install, there is currently no logic to check if there are already Stormcloud artifacts on disk in the install location.

Ideally, we should "detect" if an install is present, and if one is, give the user an option to overwrite their previous install or bail out. If they want to overwrite, the installer should overwrite the Stormcloud folder and create a new one.

Estimated story points: 6

**Comment by EccentricKnight** [comment]
Closing as there is a more recent issue: https://github.com/runt1me/stormcloud/issues/90
